#!/bin/sh
# Keep playing one note over and over, but reload the patch regularly

while true
do
  (
    echo edit
    echo  clr 1
    echo  sel 0 1
    echo  pat 100 100 100 '; Bunch of space, just in case'
    cat   "$1"
    echo  end
    echo end

    for n in 60 60 60 60
    do
      echo freq 0 0 $((n << 24))
      echo ampl 0 0 $((16777216))
      echo keyd 0 0
      echo run 7000
      echo keyu 0 0
      echo run 1000
    done
    echo run 16000
    echo end
  ) |
  ./fmsynth 2>/dev/null
done |
aplay -r48000 -c1 -fS16_LE
