#!/bin/sh
# Keep playing one note over and over, but reload the patch regularly

case "$2" in
treble)
  PATTERN="84 96 96 84 96 84 84 96 84 96 96 84 84 96 84 84"
  ON=4500
  OFF=500
  ;;
bass)
  PATTERN="33 40 45  33 40 43  38 40  33 40 45 33  43 40 38 40"
  ON=6000
  OFF=1000
  ;;
"")
  PATTERN="60 60 60 60"
  ON=7000
  OFF=1000
  ;;
*)
  PATTERN="$2"
  ON=7000
  OFF=1000
  ;;
esac

while true
do
  (
    echo edit
    echo  clr 1
    echo  sel 0 1
    echo  pat 100 100 100 '; Bunch of space, just in case'
    cat   "$1"
    echo  end
    echo end

    for n in $PATTERN
    do
      echo freq 0 0 $((n << 24))
      echo ampl 0 0 $((16777216))
      echo keyd 0 0
      echo run "$ON"
      echo keyu 0 0
      echo run "$OFF"
    done
  ) |
./fmsynth 2>/dev/null
done |
aplay -r48000 -c1 -fS16_LE
